---
name: Object-Simple-Constraint
version: 0.01_01
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Constraint functions for Object::Simple;
license: perl
resources:
  license: ~
requires:
  Scalar::Util: 1.14
build_requires:
  Test::More: 0
provides:
  Object::Simple::Constraint:
    file: lib/Object/Simple/Constraint.pm
    version: 0.01_01
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
